version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Sai@6303
      MYSQL_DATABASE: job_tracker
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Sai@6303
      DB_NAME: job_tracker
    ports:
      - "3000:3000"
    depends_on:
      - db
